export const TODO_ACTIONS = {
    CREATE_TODO: 'CREATE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO',
}

export const TASK_ACTIONS = {
    CREATE_TASK: 'CREATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    UPDATE_STATUS: 'UPDATE_STATUS',
}

export const TASK_STATUS = {
    NOT_STARTED: 'NOT_STARTED',
    STARTED: 'STARTED',
    DONE: 'DONE',
}